---
title: "Kmeans e mais exemplos"
author: "Nazareno Andrade"
date: "30 de março de 2016"
output: 
    html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r, message=FALSE}
require(GGally, quietly = TRUE)
require(reshape2, quietly = TRUE)
require(tidyverse, quietly = TRUE, warn.conflicts = FALSE)
library(ggfortify)
library(cluster)
library(ggdendro)
library(broom)

theme_set(theme_bw())
source("github-lib.R")
```

```{r}
dw <- load_github_wide()
summary(dw)

ggpairs(select(dw, -repository_language))
# XML e Bluespec têm mais de 50 pushes / repositório e 
# outras linguagens têm também números estranhos. Filtraremos.
dw <- dw %>% 
  filter(PushEvent < 50, IssuesEvent < 50, ForkEvent < 18)
```

As variáveis são bastante assimétricas e concentradas em pequenos valores. Transformá-las para log ajuda na visualização.

```{r}
# Escala de log 
dw2 <- log(dw[,2:5])
dw2$repository_language <- dw$repository_language
ggpairs(select(dw2, -repository_language))

summary(select(dw2, -repository_language))
#dw2.scaled = scale(select(dw2, -repository_language))
dw2.scaled = select(dw2, -repository_language) %>% 
  mutate_each(funs(scale))
summary(dw2.scaled)
```


```{r}
row.names(dw2.scaled)  = dw2$repository_language
dists = dist(dw2.scaled, method = "euclidean")
hc = hclust(dists, method = "ward.D")

plot(hc, cex = .6)
plot(hc, hang = -1)

n_clusters = 4
rect.hclust(hc, k=n_clusters)

dw2$cluster = factor(cutree(hc, k=n_clusters))

dw2.scaled$repository_language = dw2$repository_language
dw2.scaled$cluster = factor(cutree(hc, k=n_clusters))

dw2.long = melt(dw2.scaled, id.vars = c("repository_language", "cluster"))

plot(silhouette(cutree(hc, k = n_clusters), dists), col = RColorBrewer::brewer.pal(n_clusters, "Set2"))

ggplot(dw2.long, aes(x = variable, y = value, group = repository_language, colour = cluster)) + 
    geom_line(alpha = 0.4) + 
    facet_wrap(~ cluster) 

```

## k-means

```{r}
toclust = dw2.scaled %>% 
    rownames_to_column(var = "language") %>% 
    select(1:5) 

dists = toclust %>% 
    select(-language) %>% 
    dist() # só para plotar silhouetas depois

km = toclust %>% 
    select(-language) %>% 
    kmeans(centers = n_clusters, nstart = 20)

km %>% 
    augment(toclust) %>% 
    gather(key = "variável", value = "valor", -language, -.cluster) %>% 
    ggplot(aes(x = `variável`, y = valor, group = language, colour = .cluster)) + 
    geom_point(alpha = 0.2) + 
    geom_line(alpha = .5) + 
    facet_wrap(~ .cluster) 

#autoplot(km, data = dw2.scaled, size = 3)
autoplot(km, data = dw2.scaled, label = TRUE)
plot(silhouette(km$cluster, dists), col = RColorBrewer::brewer.pal(n_clusters, "Set2"))

dw2.scaled$kmcluster = km$cluster
dw2.long = melt(dw2.scaled, id.vars = c("repository_language", "cluster", "kmcluster"))

table(km$cluster)

km %>% 
    augment(toclust) %>% 
    select(language, .cluster) %>% 
    filter(.cluster == 1)

```


--------------------


## K-means

```{r}
filmes = readr::read_csv("dados/filmes-scarlett-johanssson.csv")

filmes_t = filmes %>% 
    mutate(`BOX OFFICE` = scale(log10(`BOX OFFICE`)), 
           RATING = scale(RATING)) 

atribuicoes = tibble(k = 1:6) %>% 
    group_by(k) %>% 
    do(kmeans(select(filmes_t, RATING, `BOX OFFICE`), 
              centers = .$k, 
              nstart = 10) %>% augment(filmes)) # alterne entre filmes e filmes_t no augment  

atribuicoes_long = atribuicoes %>% 
    gather(key = "variavel", value = "valor", -TITLE, -k, -.cluster, -CREDIT) 

atribuicoes %>%
    ggplot(aes(x = RATING, y = `BOX.OFFICE`, label = TITLE, colour = .cluster)) + 
    geom_point() + 
    #geom_text() + 
    facet_wrap(~ k)
    #+ scale_y_log10()

# A silhoueta
dists = select(filmes_t, RATING, `BOX OFFICE`) %>% dist()
km = kmeans(select(filmes_t, RATING, `BOX OFFICE`), 
            centers = 4, 
            nstart = 10) 

silhouette(km$cluster, dists) %>% 
    plot(col = RColorBrewer::brewer.pal(4, "Set2"))
```

# Mais um exemplo

O dataset ruspini é clássico para ilustrar agrupamento.

```{r}
str(ruspini)

ggplot(ruspini, aes(x = x, y = y)) + 
  geom_point(size = 3)

summary(ruspini)

rs <- data.frame((ruspini))
rs <- data.frame(scale(ruspini))
colMeans(rs)

ggplot(rs, aes(x = x, y = y)) + 
  geom_point(size = 3)

```

## Hierárquico

```{r}
dists = dist(rs, method = "euclidean")
hc = hclust(dists, method = "ward.D")

plot(hc, hang = -1, cex = 0.8)

rect.hclust(hc, k=4)

rs$cluster = factor(cutree(hc, k=4))

ggplot(rs, aes(x = x, y = y, colour = cluster)) + 
  geom_point(size = 3) 

rs$cluster = factor(cutree(hc, k=8))
ggplot(rs, aes(x = x, y = y, colour = cluster, label = cluster)) + 
  geom_point(size = 2) + 
  geom_text(hjust = -.1, vjust = 1) + 
  xlim(0, 150)

plot(silhouette(cutree(hc, k = 4), dists))
plot(silhouette(cutree(hc, k = 6), dists))

#heatmap(as.matrix(dw2[,1:4]), Colv=F, scale='none')
#hc.data <- dendro_data(hc)
#ggdendrogram(hc.data, rotate = TRUE) + 
  #labs(title = "Agrupamento de Rustini")
```

```{r}
km <- kmeans(rs, centers=4, nstart=10)
km

autoplot(km, data = rs)

autoplot(km, data = rs, frame = TRUE)

```

## Iris

```{r}

```

