---
title: 'Inferência: foco em diferenças entre populações'
author: "Nazareno Andrade"
output: 
  html_notebook:
    theme: readable
    fig_width: 7
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(resample) # <-- Para bootstrap!
theme_set(theme_bw())
```

Usando novamente os dados extraídos do Last.fm

```{r}
lastfm = read_csv("dados/experimento-lastfm.csv")
lastfm = na.omit(lastfm)
glimpse(lastfm)

lastfm %>% ggplot(aes(news)) + geom_histogram(binwidth = 10)
lastfm %>% ggplot(aes(old)) + geom_histogram(binwidth = 10)

experiment = sample_n(lastfm, 1000)
```

## Bootstrap com bibliotecas

Temos duas bibliotecas principais. Para algumas coisas, uma funciona melhor que a outra, então conheça as duas. A primeira é a `resample`:

```{r}
median.news = bootstrap(experiment, 
                        median(news), 
                        R = 2000) %>% 
    #CI.bca(probs = c(.025, .975))
    CI.percentile(probs = c(.025, .975))
median.news 

median.old = bootstrap(experiment, median(old), R = 2000) %>% 
    CI.percentile(probs = c(.025, .975))
median.old 

# Existe também CI.bca . Se ele retornar NaN ou NA, é porque não conseguiu estimar o IC para a estatística que você escolheu com a precisão desejada. Geralmente acontece quando é uma estatística que não tem valores contínuos (ex: mediana.)

```

A outra é a `boot`:

```{r}
library(boot)
meu_theta <- function(x, i) {
    mean(x[i])
}

res.boot <- boot(data = experiment$news, 
                 statistic = meu_theta, 
                 R = 5000)

#plot(res.boot)
boot.ci(boot.out = res.boot, 
        conf = 0.95, 
        type = "basic")

boot.ci(boot.out = res.boot, 
        conf = 0.95, 
        type = "bca")

boot.ci(boot.out = res.boot, 
        conf = 0.95, 
        type = "perc")
```

## Inferência com duas amostras:

```{r}
b = bootstrap(experiment, mean(news))
mean.news = CI.bca(b, probs = c(.025, .975))
mean.news

b = bootstrap(experiment, mean(old))
mean.old = CI.bca(b, probs = c(.025, .975))
mean.old

b = bootstrap(experiment, median(old))
median.old = CI.percentile(b, probs = c(.025, .975))
median.old 

df = data.frame(rbind(mean.news, 
                      # median.news,
                      mean.old
                      # median.old
                      ))
df$medida = row.names(df)

df %>% 
  ggplot(aes(x = medida, ymin = X2.5., ymax = X97.5.)) + 
  geom_errorbar(width = .2)
```

## Diferenças não pareadas

```{r}
experiment = experiment %>% 
  mutate(gosta_de_pop = mediana_pop > 5.5, 
         prop_news = news/(news + old))

# Médias dos grupos separados
b1 = experiment %>% 
  filter(gosta_de_pop == TRUE) %>%
  bootstrap(median(prop_news))

mean.gosta = b1 %>% 
  CI.percentile(probs = c(.025, .975))

b2 = experiment %>% 
  filter(gosta_de_pop != TRUE) %>%
  bootstrap(median(prop_news))
mean.naogosta = b2 %>% 
  CI.percentile(probs = c(.025, .975))

df.medias = data.frame(rbind(mean.gosta, 
                             mean.naogosta))
df.medias$medida = c("fãs de pop", "demais")

df.medias %>% 
  ggplot(aes(x = medida, ymin = X2.5., ymax = X97.5.)) + 
  geom_errorbar(width = .2)

# Agora a diferença das médias
b.diff.means = bootstrap2(experiment$prop_news, 
                          treatment = experiment$gosta_de_pop, 
                          mean)

means.diff = CI.percentile(b.diff.means, probs = c(.05, .95))
means.diff

data.frame(means.diff) %>% 
  ggplot(aes(x = "Diferença", ymin = X5., ymax = X95.)) + 
  geom_errorbar(width = .2) + 
  geom_hline(yintercept = 0, colour = "darkorange")
```

## Diferenças pareadas

```{r}
meu_theta <- function(x, i) {
    x %>% 
        slice(i) %>% 
        summarise(resultado = mean(old / news)) %>% 
        pull(resultado)
}

res.boot <- boot(data = experiment, 
                 statistic = meu_theta, 
                 R = 5000)

#plot(res.boot)
boot.ci(boot.out = res.boot, 
        conf = 0.95, 
        type = "basic")

```


```{r}
# NÃO PAREADO!
b = bootstrap2(data = experiment$old, 
               data2 = experiment$news, 
               median)
medians.diff = CI.percentile(b, probs = c(.025, .975))
medians.diff

# PAREADO
experiment = experiment %>% 
  mutate(difOldNews = old - news)
b = bootstrap(data = experiment$difOldNews, median)
medians.diff.paired = CI.percentile(b, probs = c(.025, .975))
medians.diff.paired

data.frame(rbind(medians.diff, medians.diff.paired)) %>% 
  ggplot(aes(x = c("não pareado", "pareado"), ymin = X2.5., ymax = X97.5.)) + 
  geom_errorbar(width = .2) 

```

## Bootstrap de estatísticas menos óbvias

```{r}
experiment = sample_n(lastfm, 1000)

fun.boot <- function(dados, indices) {
    d = dados[indices,]
    correlacao = cor(d$news, d$old)
    return(correlacao)
}

res.boot <- boot(data = experiment, 
                 statistic = fun.boot, 
                 R = 2000)
plot(res.boot)
boot.ci(boot.out = res.boot, conf = 0.95, type = "bca")
```

